// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagementAPI.Data;

#nullable disable

namespace ProjectManagementAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726135202_AddPageStatusConstraint")]
    partial class AddPageStatusConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagementAPI.Models.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccessRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_root_id");

                    b.PrimitiveCollection<Guid[]>("AncestorIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("ancestor_ids")
                        .HasDefaultValueSql("'{}'::uuid[]");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<JsonDocument>("Computed")
                        .HasColumnType("jsonb")
                        .HasColumnName("computed");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cover_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Depth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("depth");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("icon");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("LastEditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_edited_by");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<JsonDocument>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rank")
                        .UseCollation("C");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_pages_workspace_id_id");

                    b.HasIndex("DatabaseId", "Rank")
                        .HasDatabaseName("ix_pages_database_id_rank");

                    b.HasIndex("WorkspaceId", "AccessRootId")
                        .HasDatabaseName("ix_pages_workspace_id_access_root_id");

                    b.HasIndex("WorkspaceId", "ParentId", "Rank")
                        .HasDatabaseName("ix_pages_workspace_id_parent_id_rank");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageAcl", b =>
                {
                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subject_type");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("PageId", "SubjectType", "SubjectId")
                        .HasName("pk_page_acls");

                    b.HasIndex("WorkspaceId", "PageId")
                        .HasDatabaseName("ix_page_acls_workspace_id_page_id");

                    b.HasIndex("PageId", "SubjectType", "SubjectId")
                        .HasDatabaseName("ix_page_acls_page_id_subject_type_subject_id");

                    b.ToTable("page_acls", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageDocSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("ByteSize")
                        .HasColumnType("integer")
                        .HasColumnName("byte_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trusted");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<byte[]>("Snapshot")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("snapshot");

                    b.Property<long>("UpToSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("up_to_seq");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_page_doc_snapshots");

                    b.HasIndex("PageId", "UpToSeq")
                        .IsUnique()
                        .HasDatabaseName("ix_page_doc_snapshots_page_id_up_to_seq");

                    b.HasIndex("WorkspaceId", "PageId")
                        .HasDatabaseName("ix_page_doc_snapshots_workspace_id_page_id");

                    b.ToTable("page_doc_snapshots", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageDocUpdate", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<byte[]>("Update")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("update_data");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<long?>("YClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("y_client_id");

                    b.HasKey("Seq")
                        .HasName("pk_page_doc_updates");

                    b.HasIndex("PageId", "Seq")
                        .HasDatabaseName("ix_page_doc_updates_page_id_seq");

                    b.HasIndex("WorkspaceId", "PageId")
                        .HasDatabaseName("ix_page_doc_updates_workspace_id_page_id");

                    b.ToTable("page_doc_updates", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageLink", b =>
                {
                    b.Property<Guid>("SourcePageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_page_id");

                    b.Property<Guid>("TargetPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_page_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("SourcePageId", "TargetPageId")
                        .HasName("pk_page_links");

                    b.HasIndex("WorkspaceId", "SourcePageId")
                        .HasDatabaseName("ix_page_links_workspace_id_source_page_id");

                    b.HasIndex("WorkspaceId", "TargetPageId")
                        .HasDatabaseName("ix_page_links_workspace_id_target_page_id");

                    b.ToTable("page_links", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageSearch", b =>
                {
                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<Guid>("AccessRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_root_id");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("body_text");

                    b.Property<Guid?>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_text")
                        .HasComputedColumnSql("title || ' ' || body_text", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("PageId")
                        .HasName("pk_page_searches");

                    b.HasIndex("WorkspaceId", "AccessRootId")
                        .HasDatabaseName("ix_page_searches_workspace_id_access_root_id");

                    b.HasIndex("WorkspaceId", "PageId")
                        .HasDatabaseName("ix_page_searches_workspace_id_page_id");

                    b.ToTable("page_searches", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("th")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_workspaces_deleted_at");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_slug");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("WorkspaceId", "UserId")
                        .HasName("pk_workspace_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.Page", b =>
                {
                    b.HasOne("ProjectManagementAPI.Models.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pages_workspaces_workspace_id");

                    b.HasOne("ProjectManagementAPI.Models.Page", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("WorkspaceId", "ParentId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pages_pages_workspace_id_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageAcl", b =>
                {
                    b.HasOne("ProjectManagementAPI.Models.Page", "Page")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PageId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_acls_pages_workspace_id_page_id");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageDocSnapshot", b =>
                {
                    b.HasOne("ProjectManagementAPI.Models.Page", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PageId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_doc_snapshots_pages_workspace_id_page_id");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageDocUpdate", b =>
                {
                    b.HasOne("ProjectManagementAPI.Models.Page", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PageId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_doc_updates_pages_workspace_id_page_id");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageLink", b =>
                {
                    b.HasOne("ProjectManagementAPI.Models.Page", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "SourcePageId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_links_pages_workspace_id_source_page_id");

                    b.HasOne("ProjectManagementAPI.Models.Page", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "TargetPageId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_links_pages_workspace_id_target_page_id");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.PageSearch", b =>
                {
                    b.HasOne("ProjectManagementAPI.Models.Page", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PageId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_searches_pages_workspace_id_page_id");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("ProjectManagementAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.WorkspaceMember", b =>
                {
                    b.HasOne("ProjectManagementAPI.Models.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_users_user_id");

                    b.HasOne("ProjectManagementAPI.Models.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.Page", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("ProjectManagementAPI.Models.Workspace", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
